apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MLFLOW_TRACKING_URI: {{ .Values.config.mlflowTrackingUri | quote }}
  MODEL_ALIAS: {{ .Values.config.modelAlias | quote }}
